# note : $SSH_AUTH_SOCK MUST be defined before running this, else you'll get a "volume name is too short" error.
# buildTag.sh does this for you.
version: "2"
services:
  buildcontainer:
    build:
      context: .
      dockerfile: Dockerfile-build
    container_name: buildcontainer
    restart: unless-stopped
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
    - $SSH_AUTH_SOCK:/ssh-agent
